name: afrione-webapp
project: afrione-api-project
namespace: sandbox
values: |-
  fullnameOverride: afrione-webapp
  image: 
    repository: afrioneltd/afrione-webapp:app-49
  namespace: sandbox
  containerPort: 3000
  autoscaling:
    enabled: false
  role:
    enabled: true
  ingress:
    host: app-sandbox
    domain: afrione.co
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
  lProbe:
    enabled: false
    path: /
    failureThreshold: 5
    periodSeconds: 5
    initialDelaySeconds: 10
  rProbe:
    enabled: false
    path: /
    failureThreshold: 5
    periodSeconds: 5
    initialDelaySeconds: 10
