name: afrione-website
project: afrione-api-project
namespace: sandbox
values: |-
  fullnameOverride: afrione-website
  image: 
    repository: afrioneltd/afrione-website:app-17
  namespace: sandbox
  containerPort: 3000
  autoscaling:
    enabled: false
  role:
    enabled: true
  ingress:
    host: site
    domain: afrione.co
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "1000Mi"
      cpu: "500m"
  lProbe:
    enabled: false
    path: /
    failureThreshold: 5
    periodSeconds: 5
    initialDelaySeconds: 10
  rProbe:
    enabled: false
    path: /
    failureThreshold: 5
    periodSeconds: 5
    initialDelaySeconds: 10
