apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: siji-proj
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers: []
spec:
  # Project description
  description: This project will hold the siji application

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
