name: afrione-adminportal
project: afrione-production-project
namespace: production
values: |-
  fullnameOverride: afrione-adminportal
  image: 
    repository: afrioneltd/afrione-admin-portal:prod-app-2
  namespace: production
  containerPort: 3000
  autoscaling:
    enabled: false
  role:
    enabled: true
  ingress:
    host: portal
    domain: afrione.co
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
  lProbe:
    enabled: false
    path: /
    failureThreshold: 5
    periodSeconds: 5
    initialDelaySeconds: 10
  rProbe:
    enabled: false
    path: /
    failureThreshold: 5
    periodSeconds: 5
    initialDelaySeconds: 10
