name: afrione-webapp
project: afrione-production-project
namespace: production
values: |-
  fullnameOverride: afrione-webapp
  image: 
    repository: afrioneltd/afrione-webapp:prod-app-21
  namespace: production
  containerPort: 3000
  autoscaling:
    enabled: false
  role:
    enabled: true
  ingress:
    host: app
    domain: afrione.co
  resources:
    requests:
      memory: "20Mi"
      cpu: "20m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  lProbe:
    enabled: false
    path: /
    failureThreshold: 5
    periodSeconds: 5
    initialDelaySeconds: 10
  rProbe:
    enabled: false
    path: /
    failureThreshold: 5
    periodSeconds: 5
    initialDelaySeconds: 10
