name: afrione-website
project: afrione-production-project
namespace: production
values: |-
  fullnameOverride: afrione-website
  image: 
    repository: afrioneltd/afrione-website:prod-app-2
  namespace: production
  containerPort: 3000
  autoscaling:
    enabled: false
  role:
    enabled: true
  ingress:
    host: ""
    domain: afrione.co
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "500Mi"
      cpu: "500m"
  lProbe:
    enabled: false
    path: /
    failureThreshold: 5
    periodSeconds: 5
    initialDelaySeconds: 10
  rProbe:
    enabled: false
    path: /
    failureThreshold: 5
    periodSeconds: 5
    initialDelaySeconds: 10
