name: afrione-api-gateway
project: afrione-api-project
namespace: afrione-api
values: |-
  fullnameOverride: afrione-api-gateway
  image: 
    repository: afrioneltd/api-gateway-service:app-3
  namespace: afrione-api
  containerPort: 3001
  managedidentity:
      enabled: true
  autoscaling:
      enabled: true
  ingress:
    enabled: true
    host: 
  lProbe:
      enabled: false
  rProbe:
      enabled: false
