name: api-gateway-service
project: afrione-api-project
namespace: sandbox
values: |-
  fullnameOverride: api-gateway-service
  image: 
    repository: afrioneltd/api-gateway-service:app-29
  namespace: sandbox
  containerPort: 9001
  resources:
    requests:
      memory: 448Mi
      cpu: 0.5
    limits:
      memory: 2Gi
      cpu: 1
  autoscaling:
    enabled: true
  ingress:
    host: api-sandbox
  lProbe:
    enabled: true
    path: /actuator/health
    failureThreshold: 5
    periodSeconds: 10
    initialDelaySeconds: 60
  rProbe:
    enabled: true
    path: /actuator/health
    failureThreshold: 5
    periodSeconds: 10
    initialDelaySeconds: 60
  envFrom:
    - secretRef:
        name: api-gateway-service
  volumeMounts:
    - name: config
      mountPath: "/config"
      readOnly: true
  volumes:
    - name: config
      configMap:
        name: api-gateway-service
