name: siji-app
project: siji-proj
namespace: siji
values: |-
  fullnameOverride: siji-app
  image: 
    repository: 
  namespace: siji
  containerPort: 3000
  managedidentity:
      enabled: true
  autoscaling:
      enabled: true
  ingress:
    enabled: true
  lProbe:
      enabled: false
  rProbe:
      enabled: false
