name: api-gateway-service
project: afrione-api-project
namespace: sandbox
values: |-
  fullnameOverride: api-gateway-service
  image: 
    repository: afrioneltd/api-gateway-service:app-30
  namespace: sandbox
  containerPort: 9001
  resources:
    requests:
      memory: 640Mi
      cpu: 0.5
    limits:
      memory: 2Gi
      cpu: 1
  autoscaling:
    enabled: true
  ingress:
    host: api-sandbox
  lProbe:
    enabled: true
    path: /actuator/health
    failureThreshold: 5
    periodSeconds: 10
    initialDelaySeconds: 60
  rProbe:
    enabled: true
    path: /actuator/health
    failureThreshold: 5
    periodSeconds: 10
    initialDelaySeconds: 60
  envFrom:
    - secretRef:
        name: api-gateway-service
  env:
    - name: AUTHORIZATION_API_GATEWAY_SERVICE_HOST
      value: http://api-gateway-service
    - name: KUBERNETES_NAMESPACE
      value: sandbox
    - name: SPRING_PROFILES_ACTIVE
      value: sandbox
    - name: SPRING_CLOUD_KUBERNETES_CONFIG_NAME
      value: api-gateway-service
    - name: SPRING_CLOUD_KUBERNETES_CONFIG_NAMESPACE
      value: sandbox
    - name: KAFKA_BROKERS_URL
      valueFrom:
        configMapKeyRef:
          name: configs
          key: KAFKA_HOST
  volumeMounts:
    - name: config
      mountPath: "/afrione/config"
      readOnly: true
  volumes:
    - name: config
      configMap:
        name: api-gateway-service
