name: api-gateway-service
project: afrione-api-project
namespace: sandbox
values: |-
  fullnameOverride: api-gateway-service
  image: 
    repository: afrioneltd/api-gateway-service:app-36
  namespace: sandbox
  containerPort: 9001
  resources:
    requests:
      memory: "1Gi"
      cpu: "1000m"
    limits:
      memory: "2000Mi"
      cpu: "1000m"
  autoscaling:
    enabled: true
  ingress:
    host: api-sandbox
  ports:
  - name: liveness-port
    containerPort: 9001
  - name: readiness-port
    containerPort: 9001
  lProbe:
    enabled: true
    httpGet:
      path: /actuator/health
      port: liveness-port
    failureThreshold: 5
    periodSeconds: 120
    initialDelaySeconds: 120
  rProbe:
    enabled: true
    httpGet:
      path: /actuator/health
      port: readiness-port
    failureThreshold: 5
    periodSeconds: 120
    initialDelaySeconds: 120
  env:
    - name: AUTHORIZATION_API_GATEWAY_SERVICE_HOST
      value: http://api-gateway-service
    - name: KUBERNETES_NAMESPACE
      value: sandbox
    - name: SPRING_PROFILES_ACTIVE
      value: sandbox
    - name: SPRING_CLOUD_KUBERNETES_CONFIG_NAME
      value: api-gateway-service
    - name: SPRING_CLOUD_KUBERNETES_CONFIG_NAMESPACE
      value: sandbox
    - name: KAFKA_BROKERS_URL
      valueFrom:
        configMapKeyRef:
          name: configs
          key: KAFKA_HOST
  volumeMounts:
    - name: config
      mountPath: "/afrione/config"
      readOnly: true
  volumes:
    - name: config
      configMap:
        name: api-gateway-service
