name: metabase
project: afrione-api-project
namespace: metabase-sandbox
values: |-
  fullnameOverride: metabase
  image: 
    repository: metabase/metabase:latest
  namespace: metabase-sandbox
  containerPort: 3000
  autoscaling:
    enabled: false
  ingress:
    host: metabase
  resources:
    requests:
      memory: "300Mi"
      cpu: "250m"
    limits:
      memory: "500Mi"
      cpu: "500m"
  lProbe:
    enabled: false
    path: /actuator/health
    failureThreshold: 5
    periodSeconds: 15
    initialDelaySeconds: 120
  rProbe:
    enabled: false
    path: /actuator/health
    failureThreshold: 5
    periodSeconds: 15
    initialDelaySeconds: 120
  env:
    - name: MB_DB_TYPE
      value: "postgres"
    - name: MB_DB_DBNAME
      value: "metabase"
    - name: MB_DB_PORT
      value: "5432"
    - name: MB_DB_USER
      valueFrom:
        secretKeyRef:
          name: database-secret
          key: DB_USER
    - name: MB_DB_PASS
      valueFrom:
        secretKeyRef:
          name: database-secret
          key: DB_PASS
    - name: MB_DB_HOST
      valueFrom:
        secretKeyRef:
          name: database-secret
          key: DB_HOST
